label: Tab navigation
status: ready
preview: '@dkfds-framed'

context:
  tabnavlist:
    items: &default_links
      - title: Tabnav 1
      - title: Tabnav 2
        active: true
      - title: Tabnav 3
      - title: Tabnav 4
      - title: Tabnav 5
