label: Badge
status: ready
preview: '@dkfds-framed'

variants:
  - name: default
    label: Examples


context:
  badge_example:
    items:
      - class: 'large'
        label: 'Stort badge'
        state: 'large'


      - class: 'small'
        label: 'Lille badge'
        state: 'small'
