label: Dato-input
status: ready
preview: '@dkfds-framed'

context:
  datoinput_example:
    items:
      - label: Indsendelsesfrist
        hint: "For eksempel: 05 12 2018"
        day: "Dag"
        month: "Måned"
        year: "År"
