label: Tekst-input
status: ready
preview: '@dkfds-framed'

context:
  textinput_example:
    items:
      - id: input-type-text
        label: Inputfelt med label
        name: input-type-text
        hint: Fx 12345678
      - id: input-focus
        label: Inputfelt i fokus
        class: focus
        name: input-focus
      - id: form-error
        name: form-error
        label: Inputfelt med fejl
        error: Hjælpsom fejlbesked
        hint: Fx 12345678
      - id: input-disabled
        label: Inputfelt som er låst
        disabled: true
      - id: input-optinal
        label: Inputfelt som er valgfrit
        optionallabel: (frivilligt)
      - id: input-readonly
        label: Inputfelt som er readonly
        readonly: true
        value: 012345-6789
